core/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from graphene_django.views import GraphQLView

from core import views
from core.schemas.schema import schema

app_name = 'core'

urlpatterns = [
    path('graphql', csrf_exempt(GraphQLView.as_view(graphiql=True, schema=schema))),
    path('authors/', views.Author.as_view(), name='authors'),
    path('publishers/', views.Publisher.as_view(), name='publishers'),
    path('genres/', views.Genre.as_view(), name='genres'),
    path('books/', views.Book.as_view(), name='books'),
    path('', views.Index.as_view(), name='index'),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
]

core/models.py
from django.db import models
from openpyxl.workbook import Workbook


class Author(models.Model):
    surname = models.CharField('Фамилия', max_length=255)
    first_name = models.CharField('Имя', max_length=255)
    patronymic = models.CharField('Отчество', max_length=255)
    birthday = models.DateField('Дата рождения')

    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'
        ordering = ('id',)

    def __str__(self) -> str:
        return f'{self.surname} {self.first_name} {self.patronymic}'

    @staticmethod
    def to_xlsx() -> Workbook:
        report = Workbook()
        ws = report.active
        ws['A1'] = 'Фамилия'
        ws['B1'] = 'Имя'
        ws['C1'] = 'Отчество'
        ws['D1'] = 'Дата рождения'

        authors = Author.objects.all()

        for index, obj in enumerate(authors, start=2):
            ws[f'A{index}'] = obj.surname
            ws[f'B{index}'] = obj.first_name
            ws[f'C{index}'] = obj.patronymic
            ws[f'D{index}'] = obj.birthday

        return report


class Genre(models.Model):
    name = models.CharField('Название', max_length=255)

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'
        ordering = ('id',)

    def __str__(self) -> str:
        return self.name

    @staticmethod
    def to_xlsx() -> Workbook:
        report = Workbook()
        ws = report.active
        ws['A1'] = 'Название'

        authors = Genre.objects.all()

        for index, obj in enumerate(authors, start=2):
            ws[f'A{index}'] = obj.name

        return report


class Publisher(models.Model):
    name = models.CharField('Название', max_length=255)

    class Meta:
        verbose_name = 'Издатель'
        verbose_name_plural = 'Издатели'
        ordering = ('id',)

    def __str__(self) -> str:
        return self.name

    @staticmethod
    def to_xlsx() -> Workbook:
        report = Workbook()
        ws = report.active
        ws['A1'] = 'Название'

        authors = Publisher.objects.all()

        for index, obj in enumerate(authors, start=2):
            ws[f'A{index}'] = obj.name

        return report


class Book(models.Model):
    title = models.CharField('Название', max_length=255)
    release_date = models.DateField('Дата выхода', null=True, blank=True)

    author = models.ForeignKey(Author, verbose_name='Автор', related_name='books', on_delete=models.PROTECT)
    genres = models.ManyToManyField(Genre, verbose_name='Жанры', related_name='books', blank=True)
    publisher = models.ForeignKey(
        Publisher, verbose_name='Издатель', related_name='books', blank=True, null=True, on_delete=models.SET_NULL
    )

    class Meta:
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'
        ordering = ('id',)

    def __str__(self) -> str:
        return f'{self.author} - {self.title} ({self.release_date})'

    @staticmethod
    def to_xlsx() -> Workbook:
        report = Workbook()
        ws = report.active
        ws['A1'] = 'Автор'
        ws['B1'] = 'Название'
        ws['C1'] = 'Дата выхода'
        ws['D1'] = 'Жанры'
        ws['E1'] = 'Издатель'
        authors = Book.objects.select_related('publisher', 'author').prefetch_related('genres')

        for index, obj in enumerate(authors, start=2):
            ws[f'A{index}'] = obj.title
            ws[f'B{index}'] = obj.release_date
            ws[f'C{index}'] = str(obj.author)
            ws[f'D{index}'] = ', '.join([str(genre) for genre in obj.genres.all()])
            ws[f'E{index}'] = str(obj.publisher)

        return report

core/views.py
from django.db.models import QuerySet
from django.views.generic import ListView, TemplateView

from core import filters, models


class Author(ListView):
    template_name = 'core/author.html'
    model = models.Author

    def get_filters(self) -> filters:
        return filters.Author(self.request.GET)

    def get_queryset(self) -> QuerySet:
        return self.get_filters().qs

    def get_context_data(self, *, object_list: list = None, **kwargs: dict) -> dict:
        context = super().get_context_data()
        context['filters'] = self.get_filters()

        return context


class Publisher(ListView):
    template_name = 'core/publisher.html'
    model = models.Publisher

    def get_filters(self) -> filters:
        return filters.Publisher(self.request.GET)

    def get_queryset(self) -> QuerySet:
        return self.get_filters().qs

    def get_context_data(self, *, object_list: list = None, **kwargs: dict) -> dict:
        context = super().get_context_data()
        context['filters'] = self.get_filters()

        return context


class Book(ListView):
    template_name = 'core/book.html'
    model = models.Book

    def get_filters(self) -> filters:
        return filters.Book(self.request.GET)

    def get_queryset(self) -> QuerySet:
        return self.get_filters().qs

    def get_context_data(self, *, object_list: list = None, **kwargs: dict) -> dict:
        context = super().get_context_data()
        context['filters'] = self.get_filters()

        return context


class Genre(ListView):
    template_name = 'core/genre.html'
    model = models.Genre

    def get_filters(self) -> filters:
        return filters.Genre(self.request.GET)

    def get_queryset(self) -> QuerySet:
        return self.get_filters().qs

    def get_context_data(self, *, object_list: list = None, **kwargs: dict) -> dict:
        context = super().get_context_data()
        context['filters'] = self.get_filters()

        return context


class Index(TemplateView):
    template_name = 'core/index.html'

core/templates/change_list.html
{% extends "admin/change_list.html" %}

{% block result_list %}
<div class="object-tools">
    <a href="{{ request.path }}save/" class="btn btn-high btn-success">Сохранить объекты</a>
</div>
{{ block.super }}
{% endblock %}

core/templates/core/author.html
{% extends 'main.html' %}
{% load bootstrap5 %}
{% block content %}

<div style="width: 50%; margin: auto; margin-top: 20px;">
    <form method="get">
        {% csrf_token %}
        {% bootstrap_form filters.form %}
        {% buttons %}
        <button type="submit" class="btn btn-primary">Поиск</button>
        {% endbuttons %}
    </form>
</div>


<table class="table">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">Фамилия</th>
      <th scope="col">Имя</th>
      <th scope="col">Отчество</th>
      <th scope="col">День рождения</th>
    </tr>
  </thead>
  <tbody>
    {% for obj in object_list %}
    <tr>
          <th scope="row">{{ obj.id }}</th>
          <td>{{ obj.surname }}</td>
          <td>{{ obj.first_name }}</td>
          <td>{{ obj.patronymic }}</td>
          <td>{{ obj.birthday }}</td>
        </tr>
    {% endfor %}
</table>

{% endblock content %}

core/templates/core/book.html
{% extends 'main.html' %}
{% load bootstrap5 %}
{% block content %}

<div style="width: 50%; margin: auto; margin-top: 20px;">
    <form method="get">
        {% csrf_token %}
        {% bootstrap_form filters.form %}
        {% buttons %}
        <button type="submit" class="btn btn-primary">Поиск</button>
        {% endbuttons %}
    </form>
</div>


<table class="table">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">Название</th>
      <th scope="col">Дата выхода</th>
      <th scope="col">Автор</th>
      <th scope="col">Жанры</th>
      <th scope="col">Издатель</th>
    </tr>
  </thead>
  <tbody>
    {% for obj in object_list %}
    <tr>
          <th scope="row">{{ obj.id }}</th>
          <td>{{ obj.title }}</td>
          <td>{{ obj.release_date }}</td>
          <td>{{ obj.author }}</td>
          <td>{% for genre in obj.genres.all %}{{ genre }}{% endfor %}</td>
          <td>{{ obj.publisher }}</td>
        </tr>
    {% endfor %}
</table>

{% endblock content %}

core/templates/core/genre.html
{% extends 'main.html' %}
{% load bootstrap5 %}
{% block content %}

<div style="width: 50%; margin: auto; margin-top: 20px;">
    <form method="get">
        {% csrf_token %}
        {% bootstrap_form filters.form %}
        {% buttons %}
        <button type="submit" class="btn btn-primary">Поиск</button>
        {% endbuttons %}
    </form>
</div>


<table class="table">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">Название</th>
    </tr>
  </thead>
  <tbody>
    {% for obj in object_list %}
    <tr>
          <th scope="row">{{ obj.id }}</th>
          <td>{{ obj.name }}</td>
        </tr>
    {% endfor %}
</table>

{% endblock content %}

core/templates/core/index.html
{% extends 'main.html' %}
{% load bootstrap5 %}
{% block content %}

{% endblock content %}

core/templates/core/publisher.html
{% extends 'main.html' %}
{% load bootstrap5 %}
{% block content %}

<div style="width: 50%; margin: auto; margin-top: 20px;">
    <form method="get">
        {% csrf_token %}
        {% bootstrap_form filters.form %}
        {% buttons %}
        <button type="submit" class="btn btn-primary">Поиск</button>
        {% endbuttons %}
    </form>
</div>


<table class="table">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">Название</th>
    </tr>
  </thead>
  <tbody>
    {% for obj in object_list %}
    <tr>
          <th scope="row">{{ obj.id }}</th>
          <td>{{ obj.name }}</td>
        </tr>
    {% endfor %}
</table>

{% endblock content %}

templates/footer.html
<footer class="container py-5 footer navbar-fixed-bottom">
  <div class="row">
    <div class="col-12 col-md">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mb-2" role="img" viewBox="0 0 24 24"><title>Product</title><circle cx="12" cy="12" r="10"/><path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"/></svg>
      <small class="d-block mb-3 text-muted">{% now "jS F Y H:i" %}</small>
    </div>
    <div class="col-6 col-md">
      <h5>Features</h5>
      <ul class="list-unstyled text-small">
        <li><a class="link-secondary" href="#">Cool stuff</a></li>
        <li><a class="link-secondary" href="#">Random feature</a></li>
        <li><a class="link-secondary" href="#">Team feature</a></li>
        <li><a class="link-secondary" href="#">Stuff for developers</a></li>
        <li><a class="link-secondary" href="#">Another one</a></li>
        <li><a class="link-secondary" href="#">Last time</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li><a class="link-secondary" href="#">Resource name</a></li>
        <li><a class="link-secondary" href="#">Resource</a></li>
        <li><a class="link-secondary" href="#">Another resource</a></li>
        <li><a class="link-secondary" href="#">Final resource</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li><a class="link-secondary" href="#">Business</a></li>
        <li><a class="link-secondary" href="#">Education</a></li>
        <li><a class="link-secondary" href="#">Government</a></li>
        <li><a class="link-secondary" href="#">Gaming</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>About</h5>
      <ul class="list-unstyled text-small">
        <li><a class="link-secondary" href="#">Team</a></li>
        <li><a class="link-secondary" href="#">Locations</a></li>
        <li><a class="link-secondary" href="#">Privacy</a></li>
        <li><a class="link-secondary" href="#">Terms</a></li>
      </ul>
    </div>
  </div>
</footer>

templates/header.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.108.0">
    <title>{{ title }}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/product/">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>


    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#712cf9">


    <style>

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>


    <!-- Custom styles for this template -->
  </head>

  <header class="p-3 text-bg-dark">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="{% url "core:index" %}" class="nav-link px-2 text-white">Главная</a></li>
          <li><a href="{% url "core:books" %}" class="nav-link px-2 text-secondary">Книги</a></li>
          <li><a href="{% url "core:publishers" %}" class="nav-link px-2 text-secondary">Издатели</a></li>
          <li><a href="{% url "core:authors" %}" class="nav-link px-2 text-secondary">Авторы</a></li>
          <li><a href="{% url "core:genres" %}" class="nav-link px-2 text-secondary">Жанры</a></li>
          <li><a href="{% url "admin:index" %}" class="nav-link px-2 text-secondary">Админка</a></li>
        </ul>

      </div>
    </div>
  </header>

templates/main.html
{% include 'header.html' %}

{% block content %}
{% endblock content %}

{% include 'footer.html' %}